"""

||| NPC QUERY SCREEN |||

TYPE 1 : SEARCH NPC INFORMATION BY NAME
    "ENTER THE NPC NAME."
        IF INPUT IS [NPC NAME]:
            RETURNS ADDRESS, BIRTHDAY, FULL SCHEDULE FOR THE DAY,
            LOVED GIFTS, WHETHER THEY ARE MARRIABLE, AND WIKI LINK

            TYPE 1 : SEE HOW MANY MORE ITEMS ARE NEEDED FOR MAX FRIENDSHIP HEARTS
                "HOW MANY HEARTS DO YOU CURRENTLY HAVE WITH [NPC NAME]?"
                "YOU NEED X MORE LOVED ITEMS, X MORE LIKED ITEMS, OR X MORE NEUTRAL ITEMS TO MAX FRIENDSHIP HEARTS"
                "YOU NEED X MORE LOVED ITEMS, X MORE LIKED ITEMS, OR X MORE NEUTRAL ITEMS TO MAX MARRIAGE HEARTS" 
                    (ONLY IF CAN MARRY NPC)
                "[FLAVOR TEXT REFLECTING CURRENT FRIENDSHIP STATUS FOR 1-3 HEARTS, 4-6 HEARTS, 7-9 HEARTS, 10+ HEARTS]"

                TYPE B : GO BACK TO THE PREVIOUS SCREEN
                TYPE M : RETURN TO THE MAIN SCREEN

            TYPE 2 : SEE ALL OF [NPC NAME]'S GIFT PREFERENCES
                TYPE 1 : SEE LOVED GIFTS               ||| LIST ALL MATCHING GIFTS IN ABC ORDER |||
                TYPE 2 : SEE LIKED GIFTS               ||| SAME FORMAT FOR EACH PREFERENCE TYPE |||
                TYPE 3 : SEE NEUTRAL GIFTS             ||| GUI-ISH DISPLAY ACROSS PROJECT |||
                TYPE 4 : SEE DISLIKED GIFTS
                TYPE 5 : SEE HATED GIFTS

                TYPE B : GO BACK TO THE PREVIOUS SCREEN
                TYPE M : RETURN TO THE MAIN SCREEN

            TYPE B : GO BACK TO THE PREVIOUS SCREEN
            TYPE M : RETURN TO THE MAIN SCREEN

TYPE 2 : SEE ALL STARDEW GIFTABLE NPCS
    [LISTS ALL NPCS IN ABC ORDER"]

    TYPE B : GO BACK TO THE PREVIOUS SCREEN
    TYPE M : RETURN TO THE MAIN SCREEN

TYPE M : RETURN TO THE MAIN SCREEN

   """