"""

 ||| ROUTE OPTIMIZER SCREEN |||

TYPE 1 : BEGIN GIFT ROUTE OPTIMIZER

    "NPC SCHEDULES CHANGE BASED ON SEVERAL FACTORS. ANSWER 4 QUESTIONS TO OPTIMIZE YOUR GIFT ROUTE"
    "IF YOU ARE JUST TESTING THIS SIMULATION, YOU MAY COPY & PASTE THE TEXT IN THE PROVIDED EXAMPLE FOR EACH QUESTION"

    "QUESTION 1 : DO YOU HAVE THESE CHARACTERS UNLOCKED?"
    "YOUR ANSWER MUST BE IN THE FORM OF Y FOR YES, N FOR NO, AND SEPARATED BY A COMMA"      ||| INPUT TO ALL LOWERCASE, REMOVE SPACES, Y/N ONLY||||
    "WIZARD, KENT, MINES DWARF, SANDY, KROBUS, LEO -> YOUR ANSWER MUST REMAIN IN THIS ORDER"
    "EXAMPLE: Y, Y, Y, N, Y, N"

    TYPE B : GO BACK TO THE PREVIOUS SCREEN
    TYPE M : RETURN TO THE MAIN SCREEN
    TYPE R : RESTART GIFT ROUTE OPTIMIZER

        [SHOW PREVIOUSLY ENTERED DATA IN GUI-ISH LAYOUT]
        "QUESTION 2 : HOW MANY FRIENDSHIP HEARTS DO YOU HAVE WITH EACH OF THESE CHARACTERS?"
        "YOUR ANSWER MUST BE IN THE FORM OF A WHOLE NUMBER FOR EACH CHARACTER AND SEPARATED BY A COMMA"      ||| REMOVE SPACES, MAX INT 14?||||
        "TYPE 0 IF YOU HAVE NO FRIENDSHIP HEARTS WITH THE CHARACTER"
        "ABIGAIL, SEBASTIAN, HALEY, ALEX, ELLIOTT, LEAH, LEO, PENNY, SAM -> YOUR ANSWER MUST REMAIN IN THIS ORDER"
        "EXAMPLE: 5, 9, 3, 5, 10, 7, 0, 3, 5"

        TYPE B : GO BACK TO THE PREVIOUS SCREEN
        TYPE M : RETURN TO THE MAIN SCREEN
        TYPE R : RESTART GIFT ROUTE OPTIMIZER

            [SHOW PREVIOUSLY ENTERED DATA IN GUI-ISH LAYOUT]
            "QUESTION 3 : HAVE YOU COMPLETED THESE GAME PROGRESS POINTS?"
            "YOUR ANSWER MUST BE IN THE FORM OF Y FOR YES, N FOR NO, AND SEPARATED BY A COMMA"      ||| INPUT TO ALL LOWERCASE, REMOVE SPACES, Y/N ONLY ||||
            "BUS SERVICE, BEACH BRIDGE REPAIR, COMMUNITY CENTER -> YOUR ANSWER MUST REMAIN IN THIS ORDER"
            "EXAMPLE: Y, Y, N"

            TYPE B : GO BACK TO THE PREVIOUS SCREEN
            TYPE M : RETURN TO THE MAIN SCREEN
            TYPE R : RESTART GIFT ROUTE OPTIMIZER

                [SHOW PREVIOUSLY ENTERED DATA IN GUI-ISH LAYOUT]
                "QUESTION 4 : WHAT DAY IS IT?"
                "PROVIDE THE WEEKDAY, SEASON, DATE, AND WEATHER -> YOUR ANSWER MUST REMAIN IN THIS ORDER SEPARATED BY A COMMA"
                "FOR WEATHER, USE R FOR RAIN, G FOR GREEN RAIN, OR N FOR NO RAIN"
                "EXAMPLE: WEDNESDAY, SUMMER, 22, R"

                [SHOW PREVIOUSLY ENTERED DATA IN GUI-ISH LAYOUT]
                [RETURNS LIST OF ALL NPCS IN ORDER OF ROUTE OPTIMIZATION STARTING AT 7:00 THROUGH 0:00]   ||| 24 HOUR FORMAT |||
                [EACH LINE SHOWS NPC NAME, LAST TIME LOCATION_DESCRIPTION AND NEXT LOCATION_DESCRIPTION]
                    (CHECK IF LANDS ON AN EVENT DAY THAT REMOVES CHARACTER SCHEDULE)

                TYPE B : GO BACK TO THE PREVIOUS SCREEN
                TYPE M : RETURN TO THE MAIN SCREEN
                TYPE R : RESTART GIFT ROUTE OPTIMIZER

   """
